language: cpp
compiler: gcc
dist: trusty
os: linux
before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
install:
        - sudo apt-get install -qq g++-5
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
        - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
        - cd ${TRAVIS_BUILD_DIR}
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
        - gem install coveralls-lcov

before_script:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

script:
        - cd src/
        - sudo make install
        - make -B cramer
        - make -B esempio_Fraction

after_success:
- cd ${TRAVIS_BUILD_DIR} && cd src/
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info